### ISSUE TITLE
MS Teams - Full Screen Button

### ISSUE THREAD

**Issue by juliebain** [TechnologyEnhancedLearning/DLS-LEGACY#43]
Layout of the main screen with the Fullscreen button at the bottom of the screen. Users may not notice this straight away and be aware it is available, so may be more accessible if it were at the top of the screen or somewhere where it doesn't 'fall off' the screen and you have to scroll to see it.

Ticket 4047 - Tomasina Collier, Worcestershire NHS Commissioning and Primary Care

There was overwhelming feedback from the MS Teams testers that the Fullscreen button should be moved to a more prominent position near the top of the screen.

**Comment by kevwhitt-hee** [comment]
This has been done.
